version: "3.8"

services:
  db_hobbies:
    image: postgres:16
    mem_limit: 512m
    mem_reservation: 128M
    restart: always
    cpus: 0.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - hobbies
    security_opt:
      - "no-new-privileges:true"

  hobbies:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    volumes:
      - .:/app
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    ports:
      - "8000:8000"
    depends_on:
      - db_hobbies
    networks:
      - hobbies

networks:
  hobbies:
    external: true
