version: "3.8"

services:
  db_hobbies:
    image: postgres:latest
    environment:
      POSTGRES_DB: hobbies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - hobbies

  hobbies:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_hobbies
    networks:
      - hobbies


networks:
  hobbies:
    external: true
